remember_me_checked: "1"
dd_mm_yyyy: "%d-%m-%Y"
images_limit: 6
img_tag_size: "150x150"
heigt_img_250: 250
width_img_250: 250

img_format: "image/jpeg,image/gif,image/png"
VALID_EMAIL_REGEX: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
VALID_PHONE_REGEX: "\\A\\+?[\\d\\s\\-\\(\\)]+\\z"
ADMIN: 1
USER: 0
user:
  min_len_email: 6
  max_len_email: 25
  min_len_phone: 8
  max_len_phone: 15
  max_len_address: 255
  max_len_first_name: 50
  max_len_last_name: 50
  min_len_password: 6
flight:
tour:
  max_len_name: 100
  max_duration: 30
  limit_250_250: [250, 250]
  items_per_page: 10
review:
  max_rating: 5
  min_rating: 1
booking:
  min_guests: 1
  min_price: 0
